### ISSUE TITLE
Restart multiple services

### ISSUE THREAD

**Issue by WalterPrech** [AlphaNodes/ansible-system-task#1]
Hi,
that's just a question.

Is it possible to restart multiple services?

**Comment by alexandermeindl** [comment]
You cannot use it with multiple service at the same time, but you can use multiple playbooks for it:

```
- hosts: server-name
  vars:
    system_task_name: nginx
  roles:
    - AlphaNodes.system-task
```

```
- hosts: server-name
  vars:
    system_task_name: mysql
  roles:
    - AlphaNodes.system-task
```

For multiple support it one playbook and for the same server, this role needs some work ;)
